<?php
$_helper = $this->helper(\WeltPixel\ThankYouPage\Helper\Data::class);
$orderData = $this->getData('orderdata');
$orderHelper = $this->helper(\BalloonGroup\Distributes\Helper\Order::class);
$order = $orderHelper->getOrderData($orderData);
$shipingAddress = $order->getShippingAddress();
$firstname = $shipingAddress->getFirstname();
$lastname = $shipingAddress->getLastname();
$customer_name = $firstname . ' ' . $lastname;

if(empty($customer_name)) {
    $customer_name = $order->getCustomerFirstname() . $order->getCustomerLastname();
}

$telephone_tmp = $shipingAddress->getTelephone();
$postal = $shipingAddress->getPostcode();
$city = $shipingAddress->getCity();
?>
<tr>
    <td align="center" style="font-family:Verdana, Geneva, sans-serif; font-size:1em; color:steelblue; line-height:1.2em; text-align:center;">
        Te compartimos los datos de tu Distribuidor Independiente PSA:

    </td>
</tr>
<tr>
    <td width="10">&nbsp;</td>
</tr>
<tr>
    <td align="center" style="font-family:Verdana, Geneva, sans-serif; font-size:1.0em; color:#777575;line-height:1.2em; text-align:center">
        <?= $customer_name ?><br>
        <?= $city ?><br>
        Tel:: <?= $telephone_tmp ?><br>
    </td>
</tr>
